### ISSUE TITLE
Cannot build crates that depend on quickjs-rs on Windows

### ISSUE THREAD

**Issue by Luni-4** [theduke/quickjs-rs#93]
I tried to build a project called [mdbook-katek](https://github.com/lzanini/mdbook-katex) which depends on this crate. The `patched` feature was enabled, as stated [here](https://github.com/xu-cheng/katex-rs/blob/master/Cargo.toml#L16), and I've used the `x86_64-pc-windows-gnu` target, as described in the README.

Below there is the `GitHub Action` script: 

```
jobs:

  windows-binary:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: x86_64-pc-windows-gnu # Not msvc because of quickjs-rs dependency
        override: true

    - name: Setup msys64 and mingw64
      run: |
        $Paths = "C:\msys64\mingw64\bin;C:\msys64\usr\bin"
        echo "$Paths" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "CARGO_BUILD_TARGET=x86_64-pc-windows-gnu" >> $GITHUB_ENV
   
    - name: Build mdbook-katex
      run: |
        cargo build --release --target x86_64-pc-windows-gnu
```

And this is the error that I got: https://github.com/Luni-4/mdbook-katex/runs/1765047155?check_suite_focus=true#step:5:371

 It seems the job wasn't able to find the patches contained in the `libquickjs-sys/embed/patches/` directory because the `CARGO_MANIFEST_PATH` is different. This problem does not happen on `Linux` and `MacOS` though.

Thanks in advance for your help! :)
